mutation {
  createMeal(meal: {
    name: "tomato water"
    instructions: "mix"
    feedsNumPeople: 1
    mealIngredients: [
      {
        ingredient: "water"
        unit: "ml"
        quantity: 500
      },
      {
        ingredient: "tomatoes"
        unit: "grams"
        quantity: 500
        preparation: "blended"    
      }
    ]
  }) {
    id
    ingredients {
      ingredient {
        name
      }
      preparation
      quantity {
        unit
        value
      }
    }
    instructions
    name
    servingSize
  }
}